include: package:lints/recommended.yaml

linter:
  rules:
    avoid_dynamic_calls: true
    always_declare_return_types: true

analyzer:
  enable-experiment:
    - records
  language:
      strict-casts: true
      strict-inference: true
      strict-raw-types: true