name: chessts
description: A chess library written in dart.
version: 0.0.1
homepage: https://www.github.com/jr1221/chessts.dart

environment:
  sdk: '>=3.0.0-0.0.dev <4.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.1
